server:
  port: 8080
  servlet:
    context-path: /demo

###
spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/todo_db}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:123456}
  application:
    name: demo

###
mybatis:
#  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.demo.model
  configuration:
    jdbc-type-for-null: null
    auto-mapping-behavior: full
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true


###
jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds
